# hacked from https://github.com/travis-ci/travis-ci/issues/4053#issuecomment-165096516
language: generic
os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode9.1

install: curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
script:
  - . ~/.swiftenv/init
  - . ./travis-test-all.sh
